package main

import (
	"context"

	_ "github.com/cyb3rkh4l1d/subsapi/api/docs" // generated by swag (run `swag init`)
	"github.com/cyb3rkh4l1d/subsapi/app"
	"github.com/cyb3rkh4l1d/subsapi/internal/database"
)

// @title Subscription API
// @version 1.0
// @description REST API for managing user subscriptions
// @host localhost:8080
// @BasePath /api/v1

func main() {
	defer database.ClosePgDriverConnection()
	apiApp := app.NewApp(context.Background())
	apiApp.Run()
}
