package main

import (
	"context"
	"log"

	_ "github.com/cyb3rkh4l1d/subsapi/api/docs" // generated by swag (run `swag init`)
	"github.com/cyb3rkh4l1d/subsapi/internal/app"
	"github.com/cyb3rkh4l1d/subsapi/internal/routes"
)

// @title Subscription API
// @version 1.0
// @description REST API for managing user subscriptions
// @host localhost:8080
// @BasePath /api/v1

func main() {

	ctx := context.Background()                                           // Create a root context for the application
	config := app.LoadConfig()                                            // Load configuration from .env
	apiApp := app.NewApiApp(ctx, config)                                  // Initialize the API application
	apiApp.RegisterRoutes(routes.SwaggerRoute, routes.SubscriptionRoutes) // Register all routes

	// Start the App server
	if err := apiApp.Run(); err != nil {
		log.Fatal("App encountered a fatal error:", err)
	}
}
